version: '2.1'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./data/mongodb:/data/db #you path - default: <path>:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root' #you username
      MONGO_INITDB_ROOT_PASSWORD: '6512' #you password

volumes:
  local-data:
    driver: local