version: '2.1'
services:
  msyql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql #you path - default: <path>:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'db' #you name databate
      MYSQL_ROOT_PASSWORD: '6512' # you root passd
      MYSQL_USER: 'user' #you username
      MYSQL_PASSWORD: '6512' #you passd - username
          
volumes:
  local-data:
    driver: local